# SPDX-FileCopyrightText: 2026 QuantGlass contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

from __future__ import annotations

from typing import Literal

from quantglass_sdk import IndicatorDefinition

__all__ = ["IndicatorDefinition", "IndicatorRegistry", "built_in_indicators"]


class IndicatorRegistry:
    def __init__(self) -> None:
        self._definitions: dict[str, IndicatorDefinition] = {}
        for definition in built_in_indicators():
            self.register(definition)

    def register(self, definition: IndicatorDefinition) -> None:
        self._definitions[definition.id] = definition

    def items(self) -> list[dict[str, object]]:
        return [
            definition.as_dict()
            for definition in sorted(self._definitions.values(), key=lambda item: item.id)
        ]

    def get(self, indicator_id: str) -> IndicatorDefinition | None:
        return self._definitions.get(indicator_id)


def built_in_indicators() -> tuple[IndicatorDefinition, ...]:
    computed = "computed"
    catalog = "catalog"
    return (
        _indicator(
            "ema21",
            "EMA 21",
            "trend",
            "Short trend baseline used for pullback/rejection logic.",
            ("close",),
            ("ema21",),
            computed,
            ("moving_average", "trend_following"),
        ),
        _indicator(
            "sma50",
            "SMA 50",
            "trend",
            "Intermediate trend baseline and higher-timeframe slope proxy.",
            ("close",),
            ("sma50",),
            computed,
            ("moving_average", "trend_following"),
        ),
        _indicator(
            "rsi14",
            "RSI 14",
            "momentum",
            "Primary momentum oscillator used in trend setups.",
            ("close",),
            ("rsi14",),
            computed,
            ("oscillator", "momentum"),
        ),
        _indicator(
            "rsi2",
            "RSI 2",
            "mean_reversion",
            "Fast oscillator used for range mean-reversion triggers.",
            ("close",),
            ("rsi2",),
            computed,
            ("oscillator", "mean_reversion"),
        ),
        _indicator(
            "atr14",
            "ATR 14",
            "volatility",
            "Volatility and stop-distance baseline.",
            ("high", "low", "close"),
            ("atr14",),
            computed,
            ("volatility", "risk"),
        ),
        _indicator(
            "adx14",
            "ADX 14",
            "regime",
            "Trend strength input for market-regime classification.",
            ("high", "low", "close"),
            ("adx14",),
            computed,
            ("trend_strength", "regime"),
        ),
        _indicator(
            "macd-histogram",
            "MACD Histogram",
            "momentum",
            "Momentum agreement input for confluence scoring.",
            ("close",),
            ("macd_hist",),
            computed,
            ("oscillator", "momentum"),
        ),
        _indicator(
            "bollinger-20-2",
            "Bollinger Bands 20/2",
            "mean_reversion",
            "Band, midline, and bandwidth features for range setups.",
            ("close",),
            ("bb_upper", "bb_mid", "bb_lower", "bb_bandwidth"),
            computed,
            ("volatility_band", "mean_reversion"),
        ),
        _indicator(
            "donchian-20",
            "Donchian Channel 20",
            "breakout",
            "Breakout and breakdown boundary detection.",
            ("high", "low"),
            ("donchian_high", "donchian_low"),
            computed,
            ("channel", "breakout"),
        ),
        _indicator(
            "keltner-21-atr",
            "Keltner Channel 21/ATR",
            "volatility",
            "Trend-channel context around EMA21 and ATR.",
            ("ema21", "atr14"),
            ("keltner_upper", "keltner_lower"),
            computed,
            ("volatility_band", "trend_following"),
        ),
        _indicator(
            "sma20",
            "SMA 20",
            "trend",
            "Short simple moving average for swing trend context.",
            ("close",),
            ("sma20",),
            computed,
            ("moving_average",),
        ),
        _indicator(
            "sma100",
            "SMA 100",
            "trend",
            "Longer intermediate simple moving average.",
            ("close",),
            ("sma100",),
            computed,
            ("moving_average",),
        ),
        _indicator(
            "sma200",
            "SMA 200",
            "trend",
            "Long-term trend baseline used by many equity traders.",
            ("close",),
            ("sma200",),
            computed,
            ("moving_average",),
        ),
        _indicator(
            "ema8",
            "EMA 8",
            "trend",
            "Fast exponential moving average for short-term momentum.",
            ("close",),
            ("ema8",),
            computed,
            ("moving_average",),
        ),
        _indicator(
            "ema34",
            "EMA 34",
            "trend",
            "Swing trend exponential moving average.",
            ("close",),
            ("ema34",),
            computed,
            ("moving_average",),
        ),
        _indicator(
            "ema55",
            "EMA 55",
            "trend",
            "Intermediate exponential moving average.",
            ("close",),
            ("ema55",),
            computed,
            ("moving_average",),
        ),
        _indicator(
            "wma20",
            "WMA 20",
            "trend",
            "Weighted moving average with linear recent-price emphasis.",
            ("close",),
            ("wma20",),
            computed,
            ("moving_average",),
        ),
        _indicator(
            "hma20",
            "Hull MA 20",
            "trend",
            "Low-lag Hull moving average for trend turns.",
            ("close",),
            ("hma20",),
            catalog,
            ("moving_average",),
        ),
        _indicator(
            "vwma20",
            "VWMA 20",
            "volume",
            "Volume-weighted moving average of close.",
            ("close", "volume"),
            ("vwma20",),
            computed,
            ("volume_weighted",),
        ),
        _indicator(
            "vwap-session",
            "Session VWAP",
            "volume",
            "Session volume-weighted average price.",
            ("high", "low", "close", "volume"),
            ("vwap",),
            computed,
            ("volume_weighted", "intraday"),
        ),
        _indicator(
            "anchored-vwap",
            "Anchored VWAP",
            "volume",
            "VWAP anchored to a selected event or swing point.",
            ("high", "low", "close", "volume"),
            ("anchored_vwap",),
            catalog,
            ("volume_weighted", "market_structure"),
        ),
        _indicator(
            "supertrend-10-3",
            "Supertrend 10/3",
            "trend",
            "ATR trailing trend state and stop line.",
            ("high", "low", "close"),
            ("supertrend", "supertrend_direction"),
            catalog,
            ("trend_following", "risk"),
        ),
        _indicator(
            "parabolic-sar",
            "Parabolic SAR",
            "trend",
            "Trailing stop-and-reversal trend indicator.",
            ("high", "low"),
            ("sar",),
            catalog,
            ("trend_following", "risk"),
        ),
        _indicator(
            "ichimoku",
            "Ichimoku Cloud",
            "trend",
            "Tenkan, Kijun, Senkou spans, and cloud state.",
            ("high", "low", "close"),
            ("tenkan", "kijun", "senkou_a", "senkou_b", "chikou"),
            catalog,
            ("trend_following", "support_resistance"),
        ),
        _indicator(
            "aroon-25",
            "Aroon 25",
            "trend",
            "Measures time since recent highs and lows.",
            ("high", "low"),
            ("aroon_up", "aroon_down", "aroon_osc"),
            computed,
            ("trend_strength",),
        ),
        _indicator(
            "dmi-14",
            "DMI 14",
            "trend",
            "Directional movement plus and minus components.",
            ("high", "low", "close"),
            ("di_plus", "di_minus"),
            computed,
            ("trend_strength",),
        ),
        _indicator(
            "cci20",
            "CCI 20",
            "momentum",
            "Commodity Channel Index for cyclical deviation from mean price.",
            ("high", "low", "close"),
            ("cci20",),
            computed,
            ("oscillator",),
        ),
        _indicator(
            "stochastic-14-3",
            "Stochastic 14/3",
            "momentum",
            "Percent K and D oscillator for range momentum.",
            ("high", "low", "close"),
            ("stoch_k", "stoch_d"),
            computed,
            ("oscillator", "mean_reversion"),
        ),
        _indicator(
            "stoch-rsi",
            "Stochastic RSI",
            "momentum",
            "Stochastic transform of RSI for fast momentum extremes.",
            ("close",),
            ("stoch_rsi_k", "stoch_rsi_d"),
            catalog,
            ("oscillator",),
        ),
        _indicator(
            "williams-r",
            "Williams %R",
            "momentum",
            "Close location in the recent high-low range.",
            ("high", "low", "close"),
            ("williams_r",),
            computed,
            ("oscillator",),
        ),
        _indicator(
            "roc12",
            "Rate Of Change 12",
            "momentum",
            "Percent price change over a lookback window.",
            ("close",),
            ("roc12",),
            computed,
            ("momentum",),
        ),
        _indicator(
            "momentum10",
            "Momentum 10",
            "momentum",
            "Raw price momentum over ten bars.",
            ("close",),
            ("momentum10",),
            computed,
            ("momentum",),
        ),
        _indicator(
            "trix15",
            "TRIX 15",
            "momentum",
            "Triple-smoothed EMA rate-of-change oscillator.",
            ("close",),
            ("trix15",),
            catalog,
            ("oscillator", "momentum"),
        ),
        _indicator(
            "ppo",
            "Percentage Price Oscillator",
            "momentum",
            "MACD-like oscillator expressed as a percentage.",
            ("close",),
            ("ppo", "ppo_signal", "ppo_hist"),
            catalog,
            ("oscillator", "momentum"),
        ),
        _indicator(
            "ultimate-oscillator",
            "Ultimate Oscillator",
            "momentum",
            "Multi-timeframe buying pressure oscillator.",
            ("high", "low", "close"),
            ("ultimate_osc",),
            catalog,
            ("oscillator",),
        ),
        _indicator(
            "awesome-oscillator",
            "Awesome Oscillator",
            "momentum",
            "Median-price momentum oscillator.",
            ("high", "low"),
            ("awesome_osc",),
            catalog,
            ("oscillator", "momentum"),
        ),
        _indicator(
            "elder-ray",
            "Elder Ray",
            "momentum",
            "Bull and bear power relative to an EMA.",
            ("high", "low", "close"),
            ("bull_power", "bear_power"),
            catalog,
            ("momentum",),
        ),
        _indicator(
            "choppiness-14",
            "Choppiness Index 14",
            "regime",
            "Classifies trend versus chop from normalized range expansion.",
            ("high", "low", "close"),
            ("choppiness14",),
            catalog,
            ("regime", "trend_strength"),
        ),
        _indicator(
            "vhf-28",
            "Vertical Horizontal Filter 28",
            "regime",
            "Trendiness ratio of net movement to cumulative movement.",
            ("close",),
            ("vhf28",),
            catalog,
            ("regime", "trend_strength"),
        ),
        _indicator(
            "hurst-100",
            "Hurst Exponent 100",
            "regime",
            "Persistence and mean-reversion tendency estimate.",
            ("close",),
            ("hurst100",),
            catalog,
            ("statistics", "regime"),
        ),
        _indicator(
            "realized-vol-20",
            "Realized Volatility 20",
            "volatility",
            "Rolling close-to-close realized volatility.",
            ("close",),
            ("realized_vol20",),
            computed,
            ("volatility", "risk"),
        ),
        _indicator(
            "historical-vol-30",
            "Historical Volatility 30",
            "volatility",
            "Annualized rolling return volatility.",
            ("close",),
            ("historical_vol30",),
            catalog,
            ("volatility", "risk"),
        ),
        _indicator(
            "stddev-20",
            "Standard Deviation 20",
            "volatility",
            "Rolling dispersion of closing prices.",
            ("close",),
            ("stddev20",),
            computed,
            ("volatility", "statistics"),
        ),
        _indicator(
            "zscore-20",
            "Z-Score 20",
            "statistics",
            "Distance from rolling mean in standard deviations.",
            ("close",),
            ("zscore20",),
            computed,
            ("statistics", "mean_reversion"),
        ),
        _indicator(
            "percent-b",
            "Bollinger %B",
            "mean_reversion",
            "Close location within Bollinger Bands.",
            ("close", "bb_upper", "bb_lower"),
            ("percent_b",),
            catalog,
            ("volatility_band", "mean_reversion"),
        ),
        _indicator(
            "bb-squeeze",
            "Bollinger Squeeze",
            "volatility",
            "Low-bandwidth volatility contraction detector.",
            ("bb_bandwidth",),
            ("bb_squeeze",),
            catalog,
            ("volatility", "breakout"),
        ),
        _indicator(
            "keltner-squeeze",
            "Keltner Squeeze",
            "volatility",
            "Bollinger-within-Keltner compression state.",
            ("bb_upper", "bb_lower", "keltner_upper", "keltner_lower"),
            ("keltner_squeeze",),
            catalog,
            ("volatility", "breakout"),
        ),
        _indicator(
            "chaikin-volatility",
            "Chaikin Volatility",
            "volatility",
            "Rate of change in high-low range volatility.",
            ("high", "low"),
            ("chaikin_volatility",),
            catalog,
            ("volatility",),
        ),
        _indicator(
            "natr14",
            "Normalized ATR 14",
            "volatility",
            "ATR expressed as a percentage of close.",
            ("atr14", "close"),
            ("natr14",),
            computed,
            ("volatility", "risk"),
        ),
        _indicator(
            "obv",
            "On-Balance Volume",
            "volume",
            "Cumulative volume flow based on up/down closes.",
            ("close", "volume"),
            ("obv",),
            computed,
            ("volume_flow",),
        ),
        _indicator(
            "mfi14",
            "Money Flow Index 14",
            "volume",
            "Volume-weighted RSI-style oscillator.",
            ("high", "low", "close", "volume"),
            ("mfi14",),
            computed,
            ("volume_flow", "oscillator"),
        ),
        _indicator(
            "cmf20",
            "Chaikin Money Flow 20",
            "volume",
            "Accumulation/distribution pressure over a window.",
            ("high", "low", "close", "volume"),
            ("cmf20",),
            computed,
            ("volume_flow",),
        ),
        _indicator(
            "accumulation-distribution",
            "Accumulation/Distribution",
            "volume",
            "Cumulative close-location volume flow.",
            ("high", "low", "close", "volume"),
            ("ad_line",),
            catalog,
            ("volume_flow",),
        ),
        _indicator(
            "chaikin-oscillator",
            "Chaikin Oscillator",
            "volume",
            "EMA spread of the accumulation/distribution line.",
            ("high", "low", "close", "volume"),
            ("chaikin_osc",),
            catalog,
            ("volume_flow", "momentum"),
        ),
        _indicator(
            "volume-sma20",
            "Volume SMA 20",
            "volume",
            "Rolling average volume baseline.",
            ("volume",),
            ("volume_sma20",),
            computed,
            ("volume",),
        ),
        _indicator(
            "relative-volume-20",
            "Relative Volume 20",
            "volume",
            "Current volume versus rolling baseline.",
            ("volume",),
            ("relative_volume20",),
            computed,
            ("volume", "confirmation"),
        ),
        _indicator(
            "ease-of-movement",
            "Ease Of Movement",
            "volume",
            "Price movement per unit of volume.",
            ("high", "low", "volume"),
            ("ease_of_movement",),
            catalog,
            ("volume_flow",),
        ),
        _indicator(
            "force-index",
            "Force Index",
            "volume",
            "Price change multiplied by volume.",
            ("close", "volume"),
            ("force_index",),
            catalog,
            ("volume_flow", "momentum"),
        ),
        _indicator(
            "negative-volume-index",
            "Negative Volume Index",
            "volume",
            "Cumulative index focused on lower-volume days.",
            ("close", "volume"),
            ("nvi",),
            catalog,
            ("volume_flow",),
        ),
        _indicator(
            "positive-volume-index",
            "Positive Volume Index",
            "volume",
            "Cumulative index focused on higher-volume days.",
            ("close", "volume"),
            ("pvi",),
            catalog,
            ("volume_flow",),
        ),
        _indicator(
            "pivot-points-classic",
            "Classic Pivot Points",
            "support_resistance",
            "Classic floor-trader pivot, support, and resistance levels.",
            ("high", "low", "close"),
            ("pivot", "r1", "r2", "r3", "s1", "s2", "s3"),
            catalog,
            ("support_resistance",),
        ),
        _indicator(
            "pivot-points-fibonacci",
            "Fibonacci Pivot Points",
            "support_resistance",
            "Fibonacci-derived support and resistance levels.",
            ("high", "low", "close"),
            ("fib_pivot", "fib_r1", "fib_r2", "fib_r3", "fib_s1", "fib_s2", "fib_s3"),
            catalog,
            ("support_resistance",),
        ),
        _indicator(
            "fractals",
            "Williams Fractals",
            "market_structure",
            "Local swing high and swing low detection.",
            ("high", "low"),
            ("fractal_high", "fractal_low"),
            catalog,
            ("market_structure",),
        ),
        _indicator(
            "swing-pivots",
            "Swing Pivots",
            "market_structure",
            "Configurable pivot highs/lows for structure tracking.",
            ("high", "low"),
            ("swing_high", "swing_low"),
            catalog,
            ("market_structure",),
        ),
        _indicator(
            "zigzag",
            "Zig Zag",
            "market_structure",
            "Noise-filtered swing structure by percent reversal.",
            ("high", "low", "close"),
            ("zigzag",),
            catalog,
            ("market_structure",),
        ),
        _indicator(
            "break-of-structure",
            "Break Of Structure",
            "market_structure",
            "Bullish and bearish structure break states.",
            ("high", "low", "close"),
            ("bos_bullish", "bos_bearish"),
            catalog,
            ("market_structure",),
        ),
        _indicator(
            "support-resistance-zones",
            "Support/Resistance Zones",
            "market_structure",
            "Clustered historical reaction zones.",
            ("high", "low", "close", "volume"),
            ("support_zones", "resistance_zones"),
            catalog,
            ("market_structure", "support_resistance"),
        ),
        _indicator(
            "gap-detector",
            "Gap Detector",
            "market_structure",
            "Session or candle gaps by configurable threshold.",
            ("open", "high", "low", "close"),
            ("gap_up", "gap_down", "gap_percent"),
            catalog,
            ("market_structure", "data_quality"),
        ),
        _indicator(
            "fair-value-gap",
            "Fair Value Gap",
            "market_structure",
            "Three-candle imbalance zones.",
            ("high", "low"),
            ("bullish_fvg", "bearish_fvg"),
            catalog,
            ("market_structure",),
        ),
        _indicator(
            "order-block-candidates",
            "Order Block Candidates",
            "market_structure",
            "High-volume reversal candle zones for research.",
            ("open", "high", "low", "close", "volume"),
            ("bullish_order_block", "bearish_order_block"),
            catalog,
            ("market_structure",),
        ),
        _indicator(
            "linear-regression-slope",
            "Linear Regression Slope",
            "statistics",
            "Rolling least-squares trend slope.",
            ("close",),
            ("linreg_slope",),
            catalog,
            ("statistics", "trend"),
        ),
        _indicator(
            "linear-regression-channel",
            "Linear Regression Channel",
            "statistics",
            "Regression midline with deviation bands.",
            ("close",),
            ("linreg_mid", "linreg_upper", "linreg_lower"),
            catalog,
            ("statistics", "channel"),
        ),
        _indicator(
            "beta-vs-benchmark",
            "Beta Vs Benchmark",
            "relative_strength",
            "Rolling beta against a selected benchmark.",
            ("close", "benchmark_close"),
            ("beta",),
            catalog,
            ("relative_strength", "risk"),
        ),
        _indicator(
            "correlation-vs-benchmark",
            "Correlation Vs Benchmark",
            "relative_strength",
            "Rolling correlation against a selected benchmark.",
            ("close", "benchmark_close"),
            ("correlation",),
            catalog,
            ("relative_strength", "statistics"),
        ),
        _indicator(
            "relative-strength-ratio",
            "Relative Strength Ratio",
            "relative_strength",
            "Price ratio versus benchmark.",
            ("close", "benchmark_close"),
            ("relative_strength_ratio",),
            catalog,
            ("relative_strength",),
        ),
        _indicator(
            "rs-rank",
            "Relative Strength Rank",
            "relative_strength",
            "Cross-sectional percentile rank of recent returns.",
            ("close",),
            ("rs_rank",),
            catalog,
            ("relative_strength", "ranking"),
        ),
        _indicator(
            "drawdown-current",
            "Current Drawdown",
            "risk",
            "Percent below rolling equity or price high.",
            ("close",),
            ("current_drawdown",),
            catalog,
            ("risk", "statistics"),
        ),
        _indicator(
            "ulcer-index",
            "Ulcer Index",
            "risk",
            "Depth and duration of drawdowns.",
            ("close",),
            ("ulcer_index",),
            catalog,
            ("risk",),
        ),
        _indicator(
            "var-95",
            "Value At Risk 95",
            "risk",
            "Rolling empirical downside quantile.",
            ("close",),
            ("var95",),
            catalog,
            ("risk", "statistics"),
        ),
        _indicator(
            "cvar-95",
            "Conditional VaR 95",
            "risk",
            "Average loss beyond the 95 percent VaR threshold.",
            ("close",),
            ("cvar95",),
            catalog,
            ("risk", "statistics"),
        ),
        _indicator(
            "sharpe-rolling",
            "Rolling Sharpe",
            "risk",
            "Rolling excess-return Sharpe ratio.",
            ("close",),
            ("rolling_sharpe",),
            catalog,
            ("risk", "statistics"),
        ),
        _indicator(
            "sortino-rolling",
            "Rolling Sortino",
            "risk",
            "Rolling downside-deviation adjusted return ratio.",
            ("close",),
            ("rolling_sortino",),
            catalog,
            ("risk", "statistics"),
        ),
        _indicator(
            "advance-decline-line",
            "Advance/Decline Line",
            "breadth",
            "Cumulative advancing minus declining instruments.",
            ("advancers", "decliners"),
            ("ad_line_breadth",),
            catalog,
            ("breadth",),
        ),
        _indicator(
            "new-high-new-low",
            "New High/New Low",
            "breadth",
            "Breadth of instruments making new highs versus lows.",
            ("new_highs", "new_lows"),
            ("nhnl",),
            catalog,
            ("breadth",),
        ),
        _indicator(
            "percent-above-sma50",
            "Percent Above SMA 50",
            "breadth",
            "Share of universe trading above its SMA50.",
            ("close", "sma50"),
            ("percent_above_sma50",),
            catalog,
            ("breadth", "regime"),
        ),
        _indicator(
            "percent-above-sma200",
            "Percent Above SMA 200",
            "breadth",
            "Share of universe trading above its SMA200.",
            ("close", "sma200"),
            ("percent_above_sma200",),
            catalog,
            ("breadth", "regime"),
        ),
        _indicator(
            "put-call-ratio",
            "Put/Call Ratio",
            "options",
            "Options sentiment ratio of put to call volume.",
            ("put_volume", "call_volume"),
            ("put_call_ratio",),
            catalog,
            ("options", "sentiment"),
        ),
        _indicator(
            "iv-rank",
            "IV Rank",
            "options",
            "Implied volatility rank within a lookback window.",
            ("implied_volatility",),
            ("iv_rank",),
            catalog,
            ("options", "volatility"),
        ),
        _indicator(
            "iv-percentile",
            "IV Percentile",
            "options",
            "Percentile of implied volatility in its lookback distribution.",
            ("implied_volatility",),
            ("iv_percentile",),
            catalog,
            ("options", "volatility"),
        ),
        _indicator(
            "funding-rate-zscore",
            "Funding Rate Z-Score",
            "crypto_derivatives",
            "Crypto perpetual funding rate standardized versus history.",
            ("funding_rate",),
            ("funding_rate_zscore",),
            catalog,
            ("crypto", "derivatives"),
        ),
        _indicator(
            "open-interest-change",
            "Open Interest Change",
            "derivatives",
            "Rolling change in futures or options open interest.",
            ("open_interest",),
            ("open_interest_change",),
            catalog,
            ("derivatives",),
        ),
        _indicator(
            "basis-spread",
            "Basis Spread",
            "derivatives",
            "Futures basis versus spot price.",
            ("spot_close", "future_close"),
            ("basis_spread",),
            catalog,
            ("derivatives", "relative_value"),
        ),
        _indicator(
            "order-book-imbalance",
            "Order Book Imbalance",
            "microstructure",
            "Bid/ask depth imbalance near the top of book.",
            ("bid_size", "ask_size"),
            ("order_book_imbalance",),
            catalog,
            ("microstructure",),
        ),
        _indicator(
            "spread-bps",
            "Spread Bps",
            "microstructure",
            "Bid/ask spread in basis points.",
            ("bid", "ask"),
            ("spread_bps",),
            catalog,
            ("microstructure", "liquidity"),
        ),
        _indicator(
            "trade-imbalance",
            "Trade Imbalance",
            "microstructure",
            "Aggressive buy/sell volume imbalance.",
            ("buy_volume", "sell_volume"),
            ("trade_imbalance",),
            catalog,
            ("microstructure", "volume_flow"),
        ),
    )


def _indicator(
    id: str,
    name: str,
    category: str,
    description: str,
    inputs: tuple[str, ...],
    outputs: tuple[str, ...],
    maturity: Literal["computed", "catalog"],
    families: tuple[str, ...],
) -> IndicatorDefinition:
    return IndicatorDefinition(
        id=id,
        name=name,
        category=category,
        description=description,
        inputs=inputs,
        outputs=outputs,
        maturity=maturity,
        families=families,
    )
